@startuml

title 課題一覧を閲覧する 

left to right direction

actor 教員と学生 as User
boundary トップページ
control 表示する
control ログインしているか検証する
control 課題詳細ページへのリンクを表示する
control 課題一覧を取得する
entity 課題一覧

User --> トップページ
トップページ --> ログインしているか検証する
ログインしているか検証する --> 表示する : はい
表示する --> トップページ
トップページ --> 課題詳細ページへのリンクを表示する
課題詳細ページへのリンクを表示する --> 課題一覧を取得する
課題一覧を取得する --> 課題一覧

rectangle 代替フロー {
    usecase ログイン

    ログインしているか検証する --> ログイン : いいえ
}

@enduml
