@startuml

title ログインする

left to right direction

actor 教員と学生 as User
boundary ログインページ
boundary トップページ
control ログイン済みか確認する
control 認証する
control 表示する
control 取得する
entity アカウント管理
entity アカウント

User --> ログインページ
ログインページ --> ログイン済みか確認する
ログイン済みか確認する --> 認証する : いいえ
ログイン済みか確認する --> 表示する : はい
ログインページ --> 表示する
認証する --> アカウント管理 : はい
アカウント管理 -right-> 取得する
取得する -up-> アカウント
表示する --> トップページ

rectangle 代替フロー {
    control 誤りがある旨とともに表示する

    認証する --> 誤りがある旨とともに表示する : いいえ
    誤りがある旨とともに表示する --> ログインページ
}

@enduml
