@startuml

title 答案を再提出する

left to right direction

actor 学生 as User
boundary 課題詳細ページ
boundary 答案再提出ページ
control 表示する
control 文字数が長すぎないか検証する
control 提出期限内か検証する
control データベースを更新する
control 確認メッセージ付きで表示する
entity 答案

User --> 課題詳細ページ
課題詳細ページ --> 表示する : 再提出ボタンを押す
表示する --> 答案再提出ページ
答案再提出ページ --> 文字数が長すぎないか検証する : 再提出ボタンを押す
文字数が長すぎないか検証する -right-> 提出期限内か検証する : はい
提出期限内か検証する -right-> データベースを更新する : はい
データベースを更新する --> 確認メッセージ付きで表示する
データベースを更新する --> 答案
確認メッセージ付きで表示する --> 課題詳細ページ

rectangle 代替フロー {
    control 検証エラーメッセージ付きで表示する

    文字数が長すぎないか検証する --> 検証エラーメッセージ付きで表示する : いいえ
    提出期限内か検証する --> 検証エラーメッセージ付きで表示する : いいえ
    検証エラーメッセージ付きで表示する --> 答案再提出ページ
}

@enduml
