@startuml

title 答案を提出する

left to right direction

actor 学生 as User
boundary 課題詳細ページ
boundary 答案提出ページ
control 表示する
control 文字数が長すぎないか検証する
control 提出期限内か検証する
control データベースに未登録か検証する
control データベースに登録する
control 確認メッセージ付きで表示する
entity 答案

User --> 課題詳細ページ
課題詳細ページ --> 表示する : 提出ボタンを押す
表示する --> 答案提出ページ
答案提出ページ --> 文字数が長すぎないか検証する : 提出ボタンを押す
文字数が長すぎないか検証する -right-> 提出期限内か検証する : はい
提出期限内か検証する -right-> データベースに未登録か検証する : はい
データベースに未登録か検証する -right-> データベースに登録する : はい
データベースに登録する --> 確認メッセージ付きで表示する
データベースに登録する -down-> 答案
確認メッセージ付きで表示する --> 課題詳細ページ

rectangle 代替フロー {
    control 検証エラーメッセージ付きで表示する

    文字数が長すぎないか検証する --> 検証エラーメッセージ付きで表示する : いいえ
    提出期限内か検証する --> 検証エラーメッセージ付きで表示する : いいえ
    データベースに未登録か検証する --> 検証エラーメッセージ付きで表示する : いいえ
    検証エラーメッセージ付きで表示する --> 答案提出ページ
}

@enduml
