@startuml

title ユースケース図

actor 学生
actor 教員

rectangle 共通 {
    学生 --> (ログインする)
    教員 --> (ログインする)
    学生 --> (課題一覧を閲覧する)
    教員 --> (課題一覧を閲覧する)
    学生 --> (課題詳細を閲覧する)
    教員 --> (課題詳細を閲覧する)
}

rectangle 学生のみ {
    学生 --> (答案を提出する)
    学生 --> (答案を再提出する)
    学生 --> (答案と採点結果を閲覧する)
}

rectangle 教員のみ {
    教員 --> (課題を作成する)
    教員 --> (課題を編集する)
    教員 --> (答案一覧を閲覧する)
    教員 --> (提出された答案を採点する)
}

(課題一覧を閲覧する) <.. (ログインする) : <<precedes>>

@enduml
